### ISSUE TITLE
Method to test that the camera is still connected

### ISSUE THREAD

**Issue by molron** [genicam/harvesters#105]
Would it be possible to add a method to confirm that a device is still connected to the ImageAcquirer? I can't see a way to do this with the current module.

Alternatively, maybe a ConnectionError exception could be raised when attempting to fetch a buffer, etc., from a disconnected camera? The current exceptions are quite variable and make a tidy try/except approach challenging.

Thanks for the great project, BTW: this is a super useful module!

**Comment by kazunarikudo** [comment]
@molron  Hi. Thank you for your feedback.

> Thanks for the great project, BTW: this is a super useful module!

You really know how to encourage me for improvements. ;-) Anyway, I'm glad if you like them.

> Would it be possible to add a method to confirm that a device is still connected to the ImageAcquirer?

Just as a response, the answer is no, unfortunately. However, I hope you understand that I see a benefit in the use case. Please let me put it on my to-do list (but this is equivalent to keep this ticket open to not forget that).

> The current exceptions are quite variable and make a tidy try/except approach challenging.

I understand that you are saying. Such cumbersome is lead by a tool that creates a C++-Python binding that Harvester consumes. In the current design, each exception is defined as an individual exception class that irritates you but as a software developer point of view, I see a root cause where can be improved and I have just learned it actually affects Harvester users.

Anyway, the issue is located in the lower layer outside of Harvester (bet just keep relaxing, I'm the maintainer of the module) and would take a reasonable amount of time to be fixed. However, the exception issue above would lead us to be capable of supporting ARM.

I'm sorry that I can't give you an immediate solution but hope you keep paying attention to our activity. Thank you again for your kind words.

/Kazunari

**Comment by molron** [comment]
Thanks for the reply Kazunari. I understand the challenge here now.

**Comment by thanos91** [comment]
I have implemented a class that is responsible for shooting images using your very helpful module.
I use this class in a GUI built with PyQt5 and occasionally with the pressing of a button in the GUI i acquire an image. Sometimes the GUI freezes and i have to completely terminate the program and restart it. I think that this is related to the question @molron asked.  The implemented class that uses much of the code you kindly provided is as follows. Is there any way that can assure that the program is not left hanging?

class Controller:
    def __init__(self):
        self.h = Harvester()
        self.h.add_cti_file((Path(ROOT_DIR) / 'ctis' / "bgapi2_gige.cti").as_posix())
        self.h.update_device_info_list()
        print(len(self.h.device_info_list))
        self.ia = self.h.create_image_acquirer(0)

        self.ia.device.node_map.Width.value = 5472
        self.ia.device.node_map.Height.value = 3648

        self.ia.device.node_map.PixelFormat.value = 'BayerRG8'
        # ia.device.node_map.AcquisitionMode.value = 'Continuous'
        # self.ia.device.node_map.AcquisitionMode.value = 'SingleFrame'
        self.ia.start_image_acquisition()

    def shoot_image(self):
        print(self.ia, type(self.ia))
        print(self.ia.num_buffers)

        with self.ia.fetch_buffer() as buffer:
            print(buffer)
            component = buffer.payload.components[0]
            data_format = component.data_format
            print(data_format)
            if data_format in mono_location_formats or bayer_location_formats:
                print(len(component.data))
                content = component.data.reshape(component.height, component.width).copy()

            elif data_format in rgb_formats or \
                    data_format in rgba_formats or \
                    data_format in bgr_formats or \
                    data_format in bgra_formats:
                #
                content = component.data.reshape(
                    component.height, component.width,
                    int(component.num_components_per_pixel)  # Set of R, G, B, and Alpha
                ).copy()
                print(content.shape)
            # ia.stop_image_acquisition()
            else:
                print('dindnt go to bayer')


            return content

    def shoot_image_safe(self):
        try:
            return self.shoot_image()
        except Exception as e:
            print(e)
            self.close_connection()
            self.__init__()
            return self.shoot_image()

    def close_connection(self):
        self.ia.destroy()
        self.h.reset()
