### ISSUE TITLE
Running harvesters with docker

### ISSUE THREAD

**Issue by ArekMC** [genicam/harvesters#118]
Hi all, 

did anyone try to run harvesters inside a docker container?
Using a python image and a very simple example I get following error:
`You have no candidate`
From what I understand this means that harvesters cannot load the CTI files.
Everything runs great on the host machine. 
The CTI-Files are available inside the container.
I tried two different CTI-Files of two manufactures.
Pinging the cameras is possible inside the container.

If this exception is not clear, I can create a minimum example. 

Best regards and as always --> Thanks for the great work!

**Comment by ArekMC** [comment]
## How to reproduce:

#### File tree

```
├── Dockerfile
├── main.py
└── ressources
    └── ids_gevgentl_linux_x86_64bit.cti
```

#### Dockerfile

```
FROM python:3.7
ADD main.py /

RUN mkdir /ressources
COPY /ressources /ressources

RUN pip install harvesters

CMD ["python", "main.py"]
```

#### Python example

```
import os
from harvesters.core import Harvester

CTI_RESSOURCE = 'ressources/ids_gevgentl_linux_x86_64bit.cti'

print(CTI_RESSOURCE, os.path.isfile(CTI_RESSOURCE))

# Init harvester
h = Harvester()

# Add camera specific GenTL driver
print("*** Initializing camera interface...")
h.add_cti_file(CTI_RESSOURCE)
h.update_device_info_list()

# list all found cameras
print("*** Searching for GigE cameras...")
print("*** Found cameras: %d" % len(h.device_info_list))
for cnt in range(len(h.device_info_list)):
    print("*** Camera #%d:" % (cnt+1))
    print(h.device_info_list[cnt])
```

#### Create docker environment
`docker build -t harvissue .`

#### Results
Running inside docker with: `docker run harvissue`
```
ressources/ids_gevgentl_linux_x86_64bit.cti True
*** Initializing camera interface...
*** Searching for GigE cameras...
*** Found cameras: 0
```
Running on host with: `docker run harvissue`
```
ressources/ids_gevgentl_linux_x86_64bit.cti True
*** Initializing camera interface...
*** Searching for GigE cameras...
*** Found cameras: 3
```

**Comment by kazunarikudo** [comment]
@ArekMC Hi, Arek. Thank you for trying out Harvester. Could you check if the container has been fully equipped to get the GenTL Producer running? A GenTL Producer, a CTI file, is a shared library actually. So if you just grab a single CTI file then it would not work because it usually looks for other libraries to work with; some might look for environment variables, too. I mean you will have to run its installer in the container in advance; of course, you could install everything by yourself but it's error-prone from a maintenance point of view. As a general question, there are enough people have got Harvester running in a Docker container so you also should be able to make it. /Kazunari

See also: https://github.com/genicam/harvesters/wiki/FAQ#i-pointed-out-a-cti-file-but-harvester-says-the-image-doesnt-exist-part-2

**Comment by Yingliangzhe** [comment]
Hello @kazunarikudo,
have you tried the mvGenTL Acquire installed inside a docker container? 
I have installed it by using a installation script inside my docker container. But the installation at the end a reboot. 
Is it necessary to reboot my container? Or the sdk can also be used without reboot?
