### ISSUE TITLE
ia.start_acquisition() is an infinite loop

### ISSUE THREAD

**Issue by Shorlaks** [genicam/harvesters#158]
Each time I run my script it freezes python (not responding).
After doing some investigation here's what I found:

ia.start_acquisition() calls to create_raw_buffers(),   line 2300 at core
create_raw_buffers() at line 2675 loops for 16 times and appends buffers.
The weird thing is, in debug mode it loops for 16 times and returns.
in run mode its an infinite loop, never returns and freezes the app.

I edited the code to see the progress of the loop
![Untitled](https://user-images.githubusercontent.com/31376676/81657226-61ed9780-9440-11ea-86b0-476b6e2fca23.jpg)

**To Reproduce**
I just followed the code from the examples

**Expected behavior**
append 16 buffers and return

**Desktop (please complete the following information):**
 - OS: Win 10
 - Python: 3.7.4
 - Harvester: 1.2.0
 - GenTL Producer: custom
 - Camera: custom

**Comment by kazunarikudo** [comment]
@Shorlaks Hi. Could you show me the value of `num_buffers` as well?

**Comment by Shorlaks** [comment]
in debug mode, num_buffers = 16.
in run mode, num_buffers = 8787503087618

**Comment by kazunarikudo** [comment]
@Shorlaks Whoa. Would you be able to check when the value turns such a large number? I guess it's constant as long as nobody overwrites it with another.

**Comment by kazunarikudo** [comment]
@Shorlaks 8787503087618 = 0x7FE00000002. Looks like an address.

**Comment by Shorlaks** [comment]
![Untitled1](https://user-images.githubusercontent.com/31376676/81659870-ce699600-9442-11ea-82d1-831a03cd9311.jpg)

![Untitled2](https://user-images.githubusercontent.com/31376676/81659882-d1648680-9442-11ea-9049-38aea6da1bdb.jpg)

what version of python u recommend?

**Comment by kazunarikudo** [comment]
@Shorlaks 3.5, 3.6, or 3.7.

**Comment by Shorlaks** [comment]
im using 3.7.4, u mean trying 3.7.0?

**Comment by kazunarikudo** [comment]
@Shorlaks Oh, no. The latest version of the 3.7 line should be okay. I do not know which version is the latest for your machine though.

**Comment by kazunarikudo** [comment]
From the release history point of view, Python 3.7.7 is the latest in the 3.7 line as of today.

**Comment by Shorlaks** [comment]
This is so weird, line 2285 in start_acquisition()
in debug mode, self._num_buffers = 16
run mode, self._num_buffers = 8787503087618

ill keep investigating

**Comment by kazunarikudo** [comment]
@Shorlaks Thanks for the update. It's weird indeed. TJFYI, `_num_buffers` is purely a Python data and it should not change its value until it's overwritten by a Harvester consumer.

**Comment by Shorlaks** [comment]
ok, I found the source of the problem but I have no idea why its happening.
It starts with  the constructor of the image_acquirer
Initializes `_data_streams` in `_setup_data_streams()` line 2230.
`_data_streams[0].buffer_announce_min` Initialized to 2.
Somewhere along the way it changes to 8787503087618, and on line 1859 it passes the wrong value.
Im truely clueless

**Comment by Shorlaks** [comment]
@kazunarikudo hey, ive tried python 3.5 and 3.6 and the infinite loop problem is gone, I guess its exclusive to python 3.7.4.
Im having some new problems tho, first of all I dont get the right fps, i get like 30/40 instead of 250.
and every frame I get looks like this: 

![Untitled](https://user-images.githubusercontent.com/31376676/81692250-ca4f6f80-9466-11ea-9845-eb7e8f8feab3.jpg)

each frame the black portion is diffrent size, sometimes it almost takes the entire frame.
I really appreciate what you are doing for this community and if you have any ideas how to diagnose the problem ill be glad to hear

**Comment by kazunarikudo** [comment]
@Shorlaks Thank you for the update. Concerning the partly black image issue, one possibility that I can think of is a failure on the camera side. Technically speaking, a failure in the internal image memory block. That part tends to be very busy with reading and writing. As you've seen an image, it's delivered to your side anyway because there's no inconsistency in the delivered data; if there is, the image will be silently discarded. An idea that you could be able to try is to set up the same configuration for a camera from another manufacturer. If it works, it would prove the GenTL Producer can handle such a setup/image acquisition. And yes, you could try another GenTL Producer with the former camera for sure. I hope this helps to push the situation forward.

**Comment by Shorlaks** [comment]
All the camera's I have here are the same camera, and the GenTL producer is custom programmed at my place of work, so I dont have many options to perform various tests.
Ill try some things I can do and I will update you, thanks alot

**Comment by kazunarikudo** [comment]
@Shorlaks A typical approach that I used to take for such an issue was to change exposure time or frame rate; they are usually tightly coupled with the image management block. If there's a clue, the height of the black part may be changed. If the height changes, you should give the camera manufacturer a report.

**Comment by kazunarikudo** [comment]
@Shorlaks Please see the following image: I just enlarged a region of interest. You'd see a line where a sequence of valid pixels suddenly come back. It looks like the image was going to be sent but the memory management block overwrote the first part until it's released from the memory.

<img width="813" alt="Screen Shot 2020-05-12 at 22 17 48" src="https://user-images.githubusercontent.com/8652625/81696121-7e202180-949e-11ea-8c0c-235276f8ab05.png">

**Comment by Shorlaks** [comment]
Ok. thanks alot for the feedback.
Ill test it tommrow because im done for today and all the equipment is at my workplace.
btw, Ive tried my custom GenTL Producer on teledyne, flir, allied vision and basler cameras,
all of the above gave me these errors:
`Traceback (most recent call last):
  File "C:/Users/test/PycharmProjects/IP/testgige.py", line 32, in <module>
    ia.remote_device.node_map.Width.value, ia.remote_device.node_map.Height.value = 480, 385
  File "C:\Users\test\PycharmProjects\try3.5\lib\site-packages\genicam\genapi.py", line 2259, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, IInteger, name, value)
  File "C:\Users\test\PycharmProjects\try3.5\lib\site-packages\genicam\genapi.py", line 101, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "C:\Users\test\PycharmProjects\try3.5\lib\site-packages\genicam\genapi.py", line 93, in _swig_setattr_nondynamic
    object.__setattr__(self, name, value)
  File "C:\Users\test\PycharmProjects\try3.5\lib\site-packages\genicam\genapi.py", line 2351, in _set_value
    self._primal_set_value(value)
  File "C:\Users\test\PycharmProjects\try3.5\lib\site-packages\genicam\genapi.py", line 2270, in _primal_set_value
    return _genapi.IInteger__primal_set_value(self, Value, Verify)
_genapi.OutOfRangeException: The difference between Value = 385 and Min = 2 must be dividable without rest by Inc = 2. : OutOfRangeException thrown in node 'Height' while calling 'Height.SetValue()' (file 'IntegerT.h', line 79)`

Ive tried Matrix vision GenTL producer with my custom camera and the cameras i listed above and it didnt work =[

**Comment by kazunarikudo** [comment]
@Shorlaks Hi. The message is telling you the answer:

> _"The difference between Value = 385 and Min = 2 must be dividable without rest by Inc = 2"_

Does that make sense for you?

BTW, I'm not a robot that works 24/7 but am a human being who is working from Japan (GMT+9) and Harvester is one of my private nonprofit projects. I try to find a way to help you but there is a case where I can't due to some unavoidable reasons. I hope you understand the reality.

**Comment by Shorlaks** [comment]
Yes of course, I do not expect you to answer my questions at all, you are not obligated to, I do realize your a person and you have your own things going on.
Im sorry if this is the impression you got, I appreciate everything u done and doing.
Im just a simple man trying to figure out what is wrong with my camera/code

**Comment by kazunarikudo** [comment]
I'd be glad if you kindly understand that I'll try to help you when I can and it'll be my pleasure as long as there's spontaneity in the motivation.

**Comment by Shorlaks** [comment]
hey @kazunarikudo, I got an update.
My camera is Mono16 so basically I cant see anything unless I apply some kind of a filter.
Right after Im fetching the frame from the buffer Im applying a histogram equalization.
I noticed that when I apply histogram equalization or any other image processing function I get those black half frames.
I turned off the histogram equalization and now my stream is flawless.
My question is why is it happening?
can it be because the image_acquisition runs on a separate thread and when it switches threads to do some calculations the next frame isnt fully fetched?

**Comment by kazunarikudo** [comment]
@Shorlaks Is the equalization thread referring to the buffer/image after the buffer is queued back to the image acquirer? Once you queue a buffer back, the buffer is overwritten by the image acquirer. If you want to hold the image, you must copy it to another object or must finish the given task until it's queued back.

**Comment by Shorlaks** [comment]
@kazunarikudo The image acquirer is running constantly, I need to display 30 fps, so every 33ms im fetching a frame from the buffer, copying it to another object and applying equalization on that object.

**Comment by Shorlaks** [comment]
Here is a code sample from your example to reproduce the problem, I only added a little delay.
```
while cv2.waitKey(1) != 27:
    with ia.fetch_buffer() as buffer:
        component = buffer.payload.components[0]
        img = component.data.reshape(480, 385).copy()
       cv2.imshow('img', img)
       time.sleep(0.03)
```
with this delay the frames starts to brake (partly black frames)

**Comment by kazunarikudo** [comment]
@Shorlaks What would it happen with the following `assert` statement?
```
img = component.data.reshape(480, 385).copy()
assert img is not component.data
```

**Comment by Shorlaks** [comment]
@kazunarikudo nothing happens.. same behavior

**Comment by kazunarikudo** [comment]
@Shorlaks So it means Harvester does not know what `img` is, i.e., there's no way to alter the data.

**Comment by Shorlaks** [comment]
Ok, ill try some workarounds and post my findings.
Thank you very much

**Comment by Shorlaks** [comment]
> @Shorlaks So it means Harvester does not know what `img` is, i.e., there's no way to alter the data.

Hey @kazunarikudo Im not altering the data, I simply added a 1ms delay between the fetches and this results in black frames, the ndarray itself in `component.data` is messed up.
Can you please explain me this behavior?

**Comment by kazunarikudo** [comment]
@Shorlaks I will ask you a question again: Is `img` referring to the same data with `component.data`? If it isn't, how would Harvester be able to alter the data in `img` without knowing what `img` is? What would happen if you display only one image with the following code?
```
buffer = ia.fetch_buffer()
component = buffer.payload.components[0]
img = component.data.reshape(480, 385).copy()
cv2.imshow('img', img)
# buffer.queue()  # Do not call this for now.
time.sleep(60)  # Wait for some to see if the data is altered.
```
With the code above you will see a single image is being displayed until the app is terminated. If the displayed image is not altered then it would imply `img` is still referring to the same data with `component.data`.

PS. Excuse me, could you stop to call me saying "hey". I do not know who you are and at least it's obvious that we are not good old friends.

**Comment by Shorlaks** [comment]
I'm sorry Sir, I don't fully understand what you mean.
`img` holds the numpy array referenced by `component.data` (we copy the array).
`img` has the same value as in `component.data` but its not a reference to `component.data` (please correct me if I'm wrong).

I have to wrap your sample code with `cv2.waitKey` to render the frames, I also changed the sleep time to 10 sec.. it fetches 16 frames, and the 16th frame is not being altered anymore.

**Comment by kazunarikudo** [comment]
@Shorlaks Please have time to encourage yourself that there still be ideas that you can think of and try. I'm not trying to say that Harvester is innocent but it still requires your effort to prove with pieces of evidence.

```
buffer = ia.fetch_buffer()
component = buffer.payload.components[0]
original = component.data.reshape(480, 385)
img = original.copy()
assert img is not original  # They must not refer to the same object.
assert False not in np.equal(original, copied)  # Each corresponding element must be euqal.
time.sleep(60)  # Wait for some to see if the data is altered.
cv2.imshow('img', img)
# buffer.queue()  # Do not call this for now.
assert False not in np.equal(original, copied)  # Each corresponding element must still be euqal.
```

**Comment by Shorlaks** [comment]
@kazunarikudo All the asserts pass. I think the problem lies elsewhere.
It seems like if there is a delay between fetching the buffers it somehow messes up the queue_buffer/fetch_buffer mechanism.
I say this because without a delay everything is perfect, with the delay, every test I try the first 16 frames are o.k (we have 16 buffers), after all the buffers are used for the first time something goes wrong and the rest of the buffers after they are fetched are partly black.
Did you try to reproduce this problem? and did u succeed?

What I'm basically trying to do is instead of getting all the frames I can fetch, I only want to fetch a frame once every 'x' ms, is there an intended way of doing it? maybe I'm missing something.

Tried it with: 
cpython 3.5/3.6/3.7
ipython 3.5/3.6/3.7
win7, win10
4 different camera's
3 diffrent pc's

**Comment by Shorlaks** [comment]
As You can see here, after 16 frames, the data itself fetched is corrupted.. this happens only with a delay.
![Untitled](https://user-images.githubusercontent.com/31376676/82187189-b4253180-98f4-11ea-9266-509a27d20dca.jpg)

**Comment by kazunarikudo** [comment]
@Shorlaks (1) Which GenTL Producer are your working with now? (2) Have you ever tried another GenTL Producer? (3) Could you show me the line where you call `start_acquisition()`?

**Comment by Shorlaks** [comment]
@kazunarikudo 
(1) The GenTL Producer was developed at my place of work.
(2) Yes, I tried with mvAcquirer, same behavior.
(3) 
![Untitled](https://user-images.githubusercontent.com/31376676/82195003-5d255980-9900-11ea-93fc-e79f8ee3fb9a.jpg)

**Comment by kazunarikudo** [comment]
@Shorlaks Okay, so would you be able to try another camera model? As far as I hear the situation, that should be worth making a try. It's a pity to just say that you do not have anything around you right now.

**Comment by Shorlaks** [comment]
@kazunarikudo I did try several cameras before posting here.
Besides my main camera, I tried Basler aca2040-25gc and Allied Vision gc2450c.
Both of them exhibit the same behavior, on continuous fetching there's no problem.
Once I add a delay, frames get messy..

**Comment by kazunarikudo** [comment]
@Shorlaks 

> I did try several cameras before posting here.

Would the outcome be the same even if you make a try now?

Is the number of pixels that compose the black area always the same?

What would happen if you shrink the resolution? Is the size of the black are shrunk as well?

Have you ever found any workaround that the black masking phenomenon fixes?

**Comment by kazunarikudo** [comment]
@Shorlaks 

Have you enabled the jumbo frame?

What would happen if you drastically slow down the acquisition frame rate?

**Comment by kazunarikudo** [comment]
@Shorlaks 

Once you reproduced the phenomenon terminate your Python script and could you try to acquire images using another image acquisition library?

Please do not turn off the camera during the trial because I would like to check if the masked image is coming from the camera.

**Comment by Shorlaks** [comment]
@kazunarikudo 
>  Would the outcome be the same even if you make a try now?

Yes, I'm constantly changing my setups and trying new things, outcome is the same.

> Is the number of pixels that compose the black area always the same?

No, the black area is different on every frame I fetch, sometimes it almost covers the entire frame.
The only thing in common is it always starts from pixel 0,0. 

> What would happen if you shrink the resolution? Is the size of the black are shrunk as well?

No, one of my cameras is 2048X2048, another camera is 480X385... on both of them the black area is random.
![Untitled](https://user-images.githubusercontent.com/31376676/82212040-923ea580-991a-11ea-88e9-a0ef56ee8692.jpg)

![Untitled1](https://user-images.githubusercontent.com/31376676/82212105-af737400-991a-11ea-8c59-89aeeb90de70.jpg)

> Have you ever found any workaround that the black masking phenomenon fixes?

Yes, I got a thread which responsible for fetching the frames, it fetches them constantly and places them in a synchronized variable, if I have a small delay in fetching or queuing the buffers, it will start to fetch partly black frames.
I have another thread which every 30ms goes to that variable and brings the data.
This fixed the black frames problem but its not an ideal solution, first of all this workaround is very costly because I'm processing 250 frames a second when I only need 30, and also, I have a GUI in my app, and because the thread that fetches frames works constantly it sometimes blocks my UI thread or the UI thread blocks the fetching thread, either way its not ideal.

> Have you enabled the jumbo frame?

Yes

> What would happen if you drastically slow down the acquisition frame rate?

I have the same camera I use only instead of 250 frames it delivers 30, and the frames from that camera do not have black areas even with a delay.

> Once you reproduced the phenomenon terminate your Python script and could you try to acquire images using another image acquisition library?

What other image acquisition library's?

PS. I answer quickly because I'm trying to solve it all the time.
Please do not feel obligated to answer asap, you already doing more then enough, thankyou

**Comment by kazunarikudo** [comment]
@Shorlaks 

The reason why I asked you if you know a workaround is just to find a clue to debug. I’m not trying to suggest you any workaround.

As far as I hear the latest information, it sounds like the black part seems to have a logical consistency.

The one thing I can say from Harvester design point of view is the buffer is filled up by the GenTL producer.

Harvester as a GenTL consumer it just tell the producer a please where it starts to fill up the delivered image and wait for the timing where the buffer is ready to be fetched. From the fact it is hard to say there’s a line where Harvester overwrites the buffer by itself.

Instead, there could be a case where an available buffer is overwritten bu the GenTL Producer at an illegal timing; for example the producer said its available and harvester fetches the buffer but the producer illegally starts to fill up an image to the fetched buffer. However I do not think it’s not realist because you can reproduce the phenomenon using other producers.

On the other hand, it’s interesting to know the origin of the black part is always on the origin of the coordinate system. In addition, the black part consists of only 0 value pixels.

By the way, i asked you to try image acquisition libraries from other manufacturers. If the data is altered by the camera itself the phenomenon will still remain; I do not think the phenomenon remain because you have confirmed with other cameras but it’s worth trying to collect pieces of evidence.

**Comment by Shorlaks** [comment]
> available buffer is overwritten by the GenTL Producer at an illegal timing

Maybe because I added a delay, it messed up somehow the timing.
Could you try and reproduce the phenomenon on your machine? Just add a delay in the fetch_buffer() block.
I will try different image acquisition libraries, the more evidence the better

**Comment by kazunarikudo** [comment]
@Shorlaks 

I have just had a test that involves `time.sleep(n)` on a GUI app that consumes Harvester and I used a simulator instead of a camera because I do not have any tangible camera here.

 I tried `n` = `0.1`, `1`, and `10` seconds but the phenomenon was not reproduced.

One easy trick that I can imaging if I asked to reproduce the phenomenon, would be to write an app that queues back a buffer while the buffer is being referenced; I mean "checking element values of the buffer using a debugger" or "displaying the data on a GUI app" are the typical use case where the word "refer" I mean. With this trick, I should be able to reproduce the phenomenon with any camera and any GenTL Producer.

Are you sure the fetched buffer is not queued back while it's referenced? If you do not have a proper locking mechanism, you will easily be able to mess the data up.

If some threads share a buffer I would recommend you check the timings where (1) a buffer is fetched, (2) the buffer is referenced, (3) and the buffer is queued back.

**Comment by Shorlaks** [comment]
@kazunarikudo 
I copy the "image" part of the buffer to another variable, isn't it enough to make sure the data wont change when I queue the buffer back?

Lets say I do queue the buffer back while it being referenced, how come the first 16 fetches are good?
If I increase the numbers of buffers, lets say to 100, ill have 100 good frames.

**Comment by kazunarikudo** [comment]
> I copy the "image" part of the buffer to another variable, isn't it enough to make sure the data wont change when I queue the buffer back?

It's enough. Once you accomplished something with the buffer you can queue it back any time.

> If I increase the numbers of buffers, lets say to 100, ill have 100 good frames.

Yes, you would. Probably.

This is just for your information, 16 is the default number of the buffers that Harvester prepares for image acquisition.

> how come the first 16 fetches are good?

Because the first 16 fetches are not interfered with by anyone. They are queued in advance before starting image acquisition.

Once the image acquisition starts, each buffer will be filled up with an image not having any interruption.

And then, they will be fetched by your application and queue them back at the timing where your application defines.

Afterward, they dive into the circulation that involves the delay that you intentionally insert, and according to your report, the delay amount changes the are of the black part. Sounds like the fetched buffer is being overwritten by someone during the sleep.

Maybe it's worth knowing some points that Harvester is expected:

* When can the buffer data be overwritten? It's the time after the buffer is queued back to the GenTL Producer.
* When is a buffer queued back? It's the time when the `ImageAcquire.queue` method is called.
* When can a buffer be fetched? It's the time when the GenTL Producer says a buffer is ready.
* When can Harvester know if a buffer is available? It's the time when the `ImageAcquire.fetch_buffer` method is called.

> If some threads share a buffer I would recommend you check the timings where (1) a buffer is fetched, (2) the buffer is referenced, (3) and the buffer is queued back.

Have you checked the points above? You should be able to check them just relying on `buffer._buufer.frame_id` because it's unique. The expected flow shold go as follows:

1. A buffer is fetched.
2. The buffer is referenced.
3. The buffer is queued back.

The following flow is a typical case where a buffer is corrupted:

1. A buffer is fetched.
2. The buffer is unintentionally queued back (by another thread, for example) and is overwritten by the GenTL Producer.
3. The buffer is referenced (but you do not notice that it's already overwritten).
3. The buffer is queued back.

>  why cant you reproduce it?

We will see it even if we do not know the reason yet.

One thing I can tell you is the app also handles image acquisition, where the `fetch` method calls,
 by another thread.

If there's a corruption in the execution order then I should see the phenomenon that you are facing.

**Comment by kazunarikudo** [comment]
I just recalled that you were mentioning at the beginning of this ticket that `num_buffers` turns unbelievably large value in a certain circumstance. I know the issues are not related to your personality but I feel such a circumstance sounds really weird. I hope you just guess that if other users are running into the same issues that you are facing, I think this issue page would be filled up with the same report, and almost all of the people would give up to use Harvester; I mean your use case is not special at all and if it does not work Harvester turn useless for almost of the image acquisition application programs. Of course, I'm not only the author but also a user. If there's something wrong in Harvester I should also face the issues as well while I'm developing it though. Again, I am not yet trying to say that Harvester is innocent; perhaps there could be a condition that I had never tried to cover by design. However, I guess the issue can be easily reproduced by anyone.

**Comment by Shorlaks** [comment]
Don't get me wrong, Harvesters is awesome and trust me I've reviewed the code many times and clearly its a work of a professional, I'm 100% sure the issue is somewhere at my side.

About `num_buffers`, my last update about this was that downgrading to python 3.5 fixed the issue, I was wrong, it worked for a while so I thought the problem is fixed but suddenly on some RUNS `num_buffers` was 8787503087618 again, so I manually edited it to 16 at core.py (line 2674) and totally forgot about it. Do you think those 2 issues may be related?

About your explanation of the Acquirer 'flow', if I understand correctly, once I start the acquisition a thread is initialized and constantly filling N buffers with data while filling new data into the 'oldest' buffer. `fetch_buffer()` simply accessing that buffer pool and pulls a buffer, at this point we have N-1 buffers available, so `buffer.queue()` releases the buffer back to its pool, am I correct?
More tests tomorrow, Thanks for your help.

**Comment by kazunarikudo** [comment]
> Do you think those 2 issues may be related?

I do not have any evidence that allows me to relate both. However, one thing that comes to my mind is it seems to be happening on a very fundamental layer. I would not think nothing can be trusted in such a circumstance.

I will say this over and over, I will never deny a possibility where a bug comes from Harvester but if the issue is caused by a defect of the design, other users should face the issue as well. Harvester has just turned 2 years old recently and it had more than 200 people and some applications are running 24/7.

> am I correct?

It depends on the buffering mode of the GenTL Producer but your interpretation is correct.

Another thought that I can speak of is a buffer is not overwritten until it's queued to the GenTL Producer. If a GenTL Producer asynchronously overwrites a fetched buffer then nobody would be able to judge if a buffer that it's referring to is complete or not.

This is a very basic restriction that the GenTL standard defines so if the following two cases happen, (1) Harvester queues back a buffer while the buffer is consumed by you or (2) the GenTL Producer overwrites a buffer that's being consumed, then it would mean both libraries cannot be used any application that is based on image acquisition.

**Comment by Shorlaks** [comment]
@kazunarikudo It Works!
I took a clean installation of win10, newest version of mvImpactAcquirer and no more black frames!
I was using previously an older version of mvImpactAcquirer.
Also maybe I had some drivers on my others testing pc's which were blocking the mv driver.
Thank you very much! you were 100% right about everything

only problem I have now theres like a 0.5-1 sec delay between what actually happens and the frame I get

**Comment by kazunarikudo** [comment]
@Shorlaks 

I'm sorry but I do not care even if it worked or did not work for you, to be honest.

I do think the first thing you should have told me was your apology. You asked me so many questions one after another just because the issue is observed through Harvester.

As far as I know, we had to exchange over 50 messages in the last 7 days and I had to spent about 2 hours every night in my spare time after work (including Saturday and Sunday); I had to dedicate my private time because Harvester is not a regular paid job and it's just one of my private OSS projects.

As a fact, you frequently requested me to reply with the following reasonings [sic]:

* _my entire days are spent on figuring this out._
* _Can you please explain me this behavior?_
* _My question is why is it happening?_
* _why cant you reproduce it?_
* _Did you try to reproduce this problem?_

To be honest, I feel your attitute seems to be missing repect for the open source software community. I am sure there are other developers who would have a similarly negative impression that I had through communication with you.

And, in addition, the following is the conclusion from the latest issue that you involved me again:

> I took a clean installation of win10, newest version of mvImpactAcquirer and no more black frames!

I want you to take time to consider this: Who can point you out such a root cause from a third-person point of view even though you were just asking why Harvester leads such a result without checking your territory?

I am sorry but I would recommend you to moderate the alert level where you judge if you should post a message for consultation or not; in the latter case, you should spend much more hours for research by yourself to understand what is sure and what isn't.

As a person who had real experience with you in person, I might delete a post from you without any hesitation if I find the provided information is not sufficient and I hope you understand why it's deleted. I hope you understand that's a necessary action to protect the valuable time of people who love to work with Harvester.

Congratulations figuring out the root cause, anyway.

Sincerely,
Kazunari.
