### ISSUE TITLE
No acquisition with JAI CM-200 GE camera

### ISSUE THREAD

**Issue by DedieuSigma** [genicam/harvesters#164]
Hello,
I have a problem with a JAI CM-200 GE camera, when I execute the update() function, I have the following message:

> GenTL producer does not implement IFGetParentTL
> GenTL producer does not implement DevGetParentIF
> GenTL producer does not implement DSGetParentDev
> GenTL producer does not implement DSGetNumBufferParts
> GenTL producer does not implement DSGetBufferPartInfo

and when I start the acquisition with ia.start_acquisition () I exit the program without message, nothing.

Do you have a solution or an answer?

**Comment by kazunarikudo** [comment]
@DedieuSigma Hi, thank you for trying out Harvester.

> I have the following message:

It's just a logging message from a Python package that Harvester uses. I would not conclude any of the messages is irrelevant to the issue but you can leave them for now.

> Do you have a solution or an answer?

I think I have had a similar inquiry from a user before but do not know how it turned out in the end. One concern that I have is they have already stopped the support for their GenTL Producer, unfortunately. It means nothing can be done even if we found a root cause.

If you do not mind, I would like to recommend you to try GenTL Producers from Matrix Vision and Baumer. They offer people their GenTL Producers for free without any support.

Matrix Vision:
http://static.matrix-vision.com/mvIMPACT_Acquire/

Baumer:
https://www.baumer.com/ae/en/product-overview/image-processing-identification/software/baumer-gapi-sdk/c/14174

At least they are still active on the development so many people have got running with Harvester.

Regards,
Kazunari.

**Comment by DedieuSigma** [comment]
Thank very much!

It works with Gentl Producer from Baumer.

Regards
