### ISSUE TITLE
Stability of image_acquirer after update()

### ISSUE THREAD

**Issue by tobias-schuele** [genicam/harvesters#174]
Are image_acquirer objects invalidated when update() is called? In other words, if a new camera is added on-the-fly, is it sufficient to only create a new image_acquirer object for this particular camera while keeping the existing ones? Thx!

**Comment by kazunarikudo** [comment]
@tobias-schuele Hi, Tobias. Thank you for asking me a question.

> is it sufficient to only create a new image_acquirer object for this particular camera while keeping the existing ones?

A short answer is "no". You will have to release that all `Harvester` objects were holding calling its `reset` method because Harvester does not define how each available device is enumerated after the `update` method; it is defined by the GenTL Producer. /Kazunari
