### ISSUE TITLE
Support for accessing multiple cameras through a single Harvester Core object

### ISSUE THREAD

**Issue by severij** [genicam/harvesters#18]
It would be nice if Harvester would support connecting multiple cameras. This would be useful especially in the field of spectral imaging, where multiple cameras could be controlled with the same interface (Harvester).

I would imagine that this wouldn't be too difficult to implement. Connecting the devices would happen in a usual way with the `connect_device` function, but a new process would be created for the each camera to be connected. If one calls the `connect_device` function with a camera that is already connected, an exception would be raised.

**Comment by kazunarikudo** [comment]
Hi Severi,

Thank you for providing us your request!

Do you mean you would like to view and control multiple cameras in a single Harvester GUI?

Regards,
Kazunari

**Comment by severij** [comment]
I meant multiple camera support in case of Harvester Core, but now I actually noticed that this is a duplicate of issue #11. :) So closing this.

**Comment by kazunarikudo** [comment]
Thanks! Okay, I'll make a try to let Harvester Core suports multiple cameras in a single object.

**Comment by kazunarikudo** [comment]
Hi Severi (@severij ),

Let me hear your opition: Which point do you see an advantage of supporting mulitple cameras within a single Harvester Core object?

Say, the current implementation maps a Harvester Core object to a single camera and it's obvisouly minimalistic and simplest (so I like this way from maintainance point of view).

Technically speaking, this way can support multiple devices just having multiple Harvester Core objects and of course, the interface is the same because you're using the same Harvester Core object.

Actually I was thinking about supporting multiple devices within a single Harvester Core object but I have changed my mind having above perspective.

Anyway, I would highly appreciate if you could tell me your point to consider if we should make it or not. In addition, it should be very helpful if you could show some lines of code that you expect to have.

Regards,
Kazunari

**Comment by severij** [comment]
I would say there is no clear advantage, except maybe being more intuitive to the user (but that might be just me). Having a `harvester.device_info_list` with multiple cameras makes you think that you could also connect multiple cameras with that HC object, but of course this is impossible with the current implementation.

An alternative implementation would need a separate class for `Device`, which could be used like 
```
camera1 = harvester.get_device(0)  # Returns a Device object
camera2 = harvester.get_device(1)
```
or something like that. So the `Device` class would have many of the features that `Harvester` class currently has. Then the device objects could be used separately:
```
camera1.start_image_acquisition()
camera2.start_image_acquisition()

# Acquisition of images with the cameras
...

camera1.stop_image_acquisition()
camera2.stop_image_acquisition()

```

I think this way the process of connecting and disconnecting of the device could be made automatic, like for example connecting the device in the `__init__` of the `Device` and disconnecting it in the `__del__`. If there is a separate `Device` class, then the role of `Harvester` object would be handling the cti-files and listing the available cameras.

However, I'm not sure if this is any better or more difficult from the maintenance point of view. I want to add that I'm totally happy with the current implementation of Harvester, since it works just fine. :)

**Comment by kazunarikudo** [comment]
Nice :-) Okay, I've got your point and would like to take a bit more time to concider a way to implement your elegant usage. My mind had been sticking on a way to use devices within a HC object anyway and it had kept preventing to reach your idea. Thank you!
