### ISSUE TITLE
Error Reporting on add_cti_file

### ISSUE THREAD

**Issue by electronsandstuff** [genicam/harvesters#181]
**Describe the bug**
Harvesters will not throw an exception in add_cti_file even when you pass it a path to a file that does not exist.

**To Reproduce**
1. Create a new harvesters instance `h = Harvester()`
2. Add a path that does not exist `h.add_cti_file("I don't exist")`

**Expected behavior**
Function should throw an exception indicating that it failed and the file does not exist or is not a CTI file.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python: 3.8
 - Harvester: 1.0.4
 - GenTL Producer: Matrix Vision
 - Camera: Prosilica GC650

**Comment by electronsandstuff** [comment]
Update: I have also tested on the most recent release of Harvesters available on pypi for Windows (1.2.6).  Same issue appears here, but replace with the newer interface (`add_file` instead of `add_cti_file`).

The reason I ran into this problem was that I was debugging an issue where I was unable to see gige cameras attached to my device while using the Matrix Vision producer.  It ended up being the same problem as in issue #132 where the path to my CTI file had control characters in it.  Python's string handling would convert them and the path passed to harvesters no longer pointed to a real file.

What is your policy on contribution, by the way?  I like this project and this seems like a simple code change.  If you're OK with it and I have the time, I could look into making a pull request.

**Comment by kazunarikudo** [comment]
@electronsandstuff Hi, thank you for your comment. I would like to tell you that my intention is different from the one you have. It is totally okay to add anything through the `add_file` method and I want users to recognize if they have available devices after calling the `update` method. If there's no available device then you will notice `len(h.device_info_list)` returns 0. In short, I do not want to block users just because they set invalid files. Of course, I understand your demand to have an exception thrown but for now, I do not see it's necessary to be honest. Could you tell me if you still have a demand on your usage? /Kazunari

**Comment by electronsandstuff** [comment]
I did not realize that this was the intended function.  Thank you for clarifying.

I was expecting to see a warning or error message from the library when I gave it an invalid parameter.  I saw that Harvesters will check if the CTI file exists and log a warning if it does not.  However, when I followed the example code in the README file, it never gets displayed.  That is what tripped me up.  The string I was entering was visually correct and the library silently failed to open it after conversion by python.  I thought that there was no way that the path I was entering could be the issue.

If the library uses a custom error handling solution, then maybe it would be a good idea to display warning messages by default and then ask more advanced users to manually disable them.  I will understand if you do not want to change this since I am, at this point, making a feature request.  However, not seeing any feedback from the library is what cost me a couple of days worth of debugging and caused a lot of frustration.  If I was not already familiar with Harvesters and just porting code to a different OS, then I am not sure I would have resolved it without a lot of help.

**Comment by kazunarikudo** [comment]
@electronsandstuff Hi. Thank you for your comment. I see your point so let me have time to find a better solution that fits Harvester.

> caused a lot of frustration

Please do not drop such words on me. Does it always enforce such a terrible situation while you are working with it? Is Harvester really always annoying for you?

I've dedicated my spare time to Harvester since 2018 to create something valuable to people all over the world. So far, so many people gave me their kind words for Harvester even if it was a feature request or a bug report. However, now I am very sad about having such uncooperative feedback.

/Kazunari

**Comment by kazunarikudo** [comment]
@electronsandstuff Hi. I have just improved Harvester so that it can cover your use case introducing two parameters, `check_existence=False` and `check_valididty=False` to the `add_cti_file/add_file` method. Note that I set `False` as their default value because I need to take care of backward compatibility. I hope it works for you. Thank you again for your feature request. /Kazunari
