### ISSUE TITLE
Harvesters Usage

### ISSUE THREAD

**Issue by Vignesh-Nswamy** [genicam/harvesters#220]
Hello all,
I intend to use harvesters with a Cheetah Pregius camera. This is all new to me so if someone can validate the steps below, it would be great.
I would have to connect the camera to my local network.
Then I will have to install harversers and a GenTL Producer.
Ideally, once this is done, my camera should be recognized by harvesters and I should be able to issue commands to my camera.

Do let me know of I am missing something. Thanks so much in advance!

**Comment by kazunarikudo** [comment]
Hi, I would suggest you following the instruction in the README.rst (or the top page of this GitHub Harvester web). It should not be difficult as you concern. Good luck! Regards, Kazunari. PS: Please do not forget that we do not talk anything about the camera-specific issues. If you have a question about the camera itself, I will highly recommend you to ask a question to your local distributor of the camera because that is their job.
