### ISSUE TITLE
How to setup remote device events?

### ISSUE THREAD

**Issue by aircleaner** [genicam/harvesters#245]
I have been trying to setup receiving remote events using Harvester/genicam. But I run into some trouble when decoding the event.

I have set it up as:
```
        event_token = image_acquirer.remote_device.register_event(EVENT_TYPE_LIST.EVENT_REMOTE_DEVICE)
        event_manager = EventManagerRemoteDevice(event_token)
        event_adapter = EventAdapterGEV()
        event_adapter.attach_node_map(node_map.pointer)
```
This works and I can then use:
```
event_manager.num_in_queue
```
To check the queue for when events have come in. But to decode I was expecting to use something like:
```
        lm = LibraryManager()
        buffer = bytes()
        length = 0
        lm.event_get_data(event_token.h_event, buffer, length, 10000)
        event_adapter.deliver_message(buffer)
        print("LogMessageLevel: ", node_map.LogMessageLevel.value)
```
But here is where I run into problems, the arguments to `lm.event_get_data()` needs to be casted, for example buffer needs to be of the type `void *`,
```
TypeError: in method 'LibraryManager_event_get_data', argument 3 of type 'void *'
```
I tried using ctypes.c_void_p but this was not accepted. What should I be using to call these functions and get my log events into the node map for "easy" access?

As a workaround I found out I can read `event_manager.optional_data` and there parse the values I need from the raw data, but this doesn't seams like a good long term solution.

**Comment by kazunarikudo** [comment]
@aircleaner Hi Jonas, please excuse me for having kept your ticket waiting such long. Finally, I've finished preparing a prototype that allows you to involve the remote device event feature; there had not had been a chance to dig this further in the previous months but finally got the chance in the last weeks. I would like to check if the change does not slow the image acquisition process so I need to ask you a favor for testing. I will create a branch for this prototype so that you can give it a try anytime when you can but it is not urgent or you are not obliged at all. When you get a chance to try it out, just let me know. Thanks, Kazunari.

**Comment by olofsjo** [comment]
@kazunarikudo thank you for the effort in trying to find a fix for this, we can of course test this, I will assign it to my college Alfred when he is back at the office.

**Comment by kazunarikudo** [comment]
Version 1.4.1 resolves the issue.
