### ISSUE TITLE
memory leak using harvesters in loop

### ISSUE THREAD

**Issue by jolu2020** [genicam/harvesters#248]
Hello,

i have some problems with continous Image aquisition with 2 cameras using the harvesters module. 

Due to unsolved issues the connection is detatched every now and than, that made me disconnect and reconnect to the cameras in each loop. This is not possible without creating a memory leak. Is there a way to delete the recent connections and objects? Sorry in advance, if the answer is rather simple and i just have a lack of knowledge in class/object relations. 

here the class (get_image-function is not of interest and shortened):

            class genicam(object):
                def __init__(self):
                    global ia
                    global ia2
                    global h
                    path_cti = r"C:\\mvGenTLProducer.cti" 
                    h = Harvester()
                    h.add_file(path_cti) 
                    h.update()
                    itemstring = []
                    for item in h.device_info_list:
                        itemstring.append(str(item))
                    camindex = [itemstring.index(i) for i in itemstring]
                    ia = h.create_image_acquirer(camindex[0])
                    ia2 = h.create_image_acquirer(camindex[1])
          
              def get_image(self, name_save, name_save_SW, ia_name, cam_nr):
                  ia_name.start_image_acquisition()
                  try: 
                      with ia_name.fetch_buffer() as buffer:
                          payload = buffer.payload
                          component = payload.components[0]
                          _1d = component.data
                          width = component.width
                          height = component.height
                          data_format = component.data_format
                          # out = ... (code skipped)
                  except Exception as e:
                      print("\n Exception")
                      print(e)
                      out = np.array(1)
                  ia_name.stop_acquisition()
                  return out 

I create the new harvester and ia-Objects in a loop and (try to) erase them as follows:

          sleeptime = 5
          
          obj_genicam = genicam()
          while loop == True: 
              """Error-Loop: Destroys all objects (ia,ia2,h) and creates new genicam-object(ia,ia2,h)
                  - repeating until all (4) successful executed"""
              error_loop = 0
              while error_loop < 4:
                  error_loop = 0
                  try: 
                      ia.destroy()
                      del ia
                      error_loop += 1
                  except Exception as e: 
                      print("\n Exception: ")
                      print(e)
                  try:
                      ia2.destroy()
                      del ia2
                      error_loop += 1
                  except Exception as e:
                      print("\n Exception: ")
                      print(e)
                  try:
                      h.reset()
                      del h
                      error_loop += 1
                  except Exception as e:
                      print("\n Exception: ")
                      print(e)   
                  try:
                      del obj_genicam
                  except Exception as e:
                      print("\n Exception: ")
                      print(e)
                  finally:
                      print("\n\ncollect garbage:")
                      garbage = gc.collect()
                      print(garbage, " garbage collected\n\n")
                  try:
                      print("- new obj_genicam ")
                      obj_genicam = genicam()
                      print("new genicam with ", ia, ia2, h)
                      error_loop += 1
                  except Exception as e:
                      print(e)
                  finally: 
                      if error_loop < 4:
                          print("error was reset: NO! \n  starting next error-loop")
                          sleep(sleeptime)
                      else: 
                          print("error was reset: YES ")
                          error = False
              print("sleep for sleeptime", sleeptime)
              sleep(sleeptime)
        

with del and gc.collect() I tried to delete the "old" objects but RAM is still rising.

I am quite new to programming and python, so i ask you to be pacient :) And thanks a lot in advance for any helping Idea.
best regards jolu

**Comment by kazunarikudo** [comment]
Hi, before getting into the detail I would like to remind you that the `del` statement does not mean the destruction of the object, i.e., the object may keep alive even if the `del` statement. This is very vital to survive the Python world. One more thing, why do you hold the involved objects in the global scope? It makes the situation worse due to the nature I brought up in the beginning because it does not leave enough options for you. You should have a way where you can surely call the `destroy` of the `ImageAcquirer` class object or the `reset` method of the `Harvester` class object. There are several options to be sure about object destruction. It is not realistic to describe everything but the `with` statement or the idea of weak reference based on the `weakref` module may help you to resolve the issue. I hope they give you practical inspiration. Good luck. Regards, Kazunari.

**Comment by tveijola** [comment]
Hello, I would like to add to this issue.

In my setup, there are three cameras (Basler Blaze-101). Each camera is operated infrequently, a single image is captured when certain conditions are met. It is somewhat important to quickly capture the image when the condition is met. Setting up the Harvester object takes time because of finding the cameras and so on. I am not familiar with the actual protocol used to find the cameras, but I expect it sends some broadcast message to the entire subnet, which is undesired in my case. To achieve quick operation and minimal network usage, a single Harvester object is created at the start of the program. This object is then used to create image acquirers for the cameras as needed. Once the image is captured, the corresponding image acquirer is destroyed using the `destroy()` method.

I noticed after leaving the program running for some days that the memory usage of the program increased over time. Following is a snippet used to create and destroy an image acquirer for a single camera multiple times. After running the program, it can be noticed that the Harvester object keeps references to destroyed ImageAcquirer objects even after they are destroyed.

    from harvesters.core import Harvester
    import os
    
    def output_ia_count(h):
        print(f"ia count: {len(h.image_acquirers)}")
    
    h = Harvester()
    cti_paths = os.getenv("GENICAM_GENTL64_PATH").split(os.pathsep)
    cti_path = f"{cti_paths[0]}\\ProducerBaslerBlazePylon.cti"
    h.add_file(cti_path)
    h.update()
    
    print("On start")
    output_ia_count(h)
    
    for i in range(5):
        ia = h.create_image_acquirer(0)
        print(f"After creating ia number {i}, ", end="")
        output_ia_count(h)
        ia.destroy()
        print(f"After destroying ia number {i}, ", end="")
        output_ia_count(h)

From my standpoint, this is not expected behaviour. I would expect that calling the `destroy` method would set the object to be taken care of by the garbage collector. As a possible solution I found that a callback may be added to each image acquirer, perhaps this could be used to remove the image acquirer from the Harvester objects ImageAcquirer list when the `destroy` method is called.

Best regards,
Tommi Veijola

**Comment by tveijola** [comment]
I did some more digging into the subject and noticed that removing the ImageAcquirers from the Harvester objects internal list is not enough. After experimenting with pympler memory tracker, I noticed some genicam objects in the summary (after capturing 25 images): 

    genicam.genapi.NodeMap          |          25 |      1.17 KB
    genicam.genapi.ChunkAdapterGEV  |          25 |      1.17 KB
    genicam.genapi._ChunkAdapterGEV |          25 |      1.17 KB

With this in mind, I turned to the `ImageAcquirer.destroy` method. I found that ImageAcquirer class contains an attribute `_chunk_adapter` of type `ChunkAdapterGEV` which in turn contains the other objects. Adding the following three lines to the `ImageAcquirer.destroy` method provided a noticable improvement to the memory usage of the program.

    self._chunk_adapter.clear_caches()
    self._chunk_adapter.detach_buffer()
    self._chunk_adapter.detach_node_map()

Could @kazunarikudo please comment on the subject? As I am not familiar with the underlying implementations I do not know the implications related to calling the above methods. Further, it is not clear to me if the issue should be resolved in the genicam package or in the harvesters package.

BR,
Tommi Veijola

**Comment by kazunarikudo** [comment]
@tveijola Hi Tommi,

Thank you very much for taking your time on this and I am sorry for having kept the silence in the last weeks; unfortunately I could not find any reasonable slot for working on Harvester in my spare time.

Yes, the leak is based on the incomplete management of the chunk adapter as you have investigated and I would like to consider the design what we need to have. I will let you know once I prepared a prototype so that you can test it if you are willing to.

Thank you again for your support.

Best regards,
Kazunari

**Comment by tveijola** [comment]
Hello,

Thank you for the reply, I understand that finding time to work on this may be difficult. I am glad that I could be of use and am certainly willing to help you out with testing once you come up with a solution.

BR,
Tommi
