### ISSUE TITLE
Connecting two GigE cameras simultenously

### ISSUE THREAD

**Issue by busyyyDog** [genicam/harvesters#264]
Hi,
there is a problem when i simultaneously connect two JAI GigE camera. While acquiring images, such error occured:
_gentl.NotAvailableException: GenTL exception: Resource or information is not available. (Message from the source: Information 'BUFFER_INFO_PAYLOADTYPE' is currently not available for this buffer) (ID: -1014)

When only connected to one camera for acquiring, everything is fine.
Does someone has similar problem, and how you solved it?

best wishes,

**Comment by kazunarikudo** [comment]
Hi, I guess packets are being dropped when two cameras are connected. In addition, there were some places to be fixed in Harvester concerning the buffer handling. The combination of two could have caused the exception. Could you give it a try with the latest master when you can? In addition, I would recommend using the Jumbo Package configuration that allows devices to send a packet that is > 1500 bytes to make the NIC relaxing. Making NIC busy can cause packet loss.

**Comment by kazunarikudo** [comment]
Please feel free to re-open this ticket if the issue can't be resolved by the latest development version of Harvester.
