### ISSUE TITLE
Get latest buffer

### ISSUE THREAD

**Issue by blaine141** [genicam/harvesters#275]
I am trying to display a live stream of my camera feed. I set the camera in continuous mode but noticed a large delay in the feed due to fetch_buffer returning the oldest buffer. 

In an attempt to get a newer buffer, I reduced the number of buffers and buffers to hold down to 2 and the delay got better. When I set them to one, though, fetch_buffer gets stuck in an infinite loop. 

Is there any way to get the newest buffer rather than the oldest buffer?

**Comment by kazunarikudo** [comment]
Hi, please excuse me for having kept you waiting. I have just created a branch, `_issue_275`, so that you can give it a try by yourself:
```
git clone https://github.com/genicam/harvesters.git && cd harvesters && git checkout -b _issue_275 origin/_issue_275 && python3 setup.py install
```
To fetch only the latest buffer, you will need to set a string `NewestOnly` to the ` buffer_handling_mode` property of the `ImageAcquirer` object:
```
ia. # type: ImageAcquire
ia.buffer_handling_mode = 'NewestOnly'
ia.start_acquisition()
# ...
```
Note that it will raise an exception if your GenTL Producer does not support `NewestOnly`. For such a situation, I recommend catching the exception by preparing a try-except block and considering switching over to another GenTL Producer that supports `NewestOnly` mode.

In addition, I need to admit that I have not tested the code with any real GenTL Producer. I would highly appreciate it if you could tell me the outcome. Please feel free to let me know if you should have any questions.

Regards, Kazunari.

**Comment by blaine141** [comment]
I tried this out and it appeared to have no impact. I also looked in the code and the value of `buffer_handling_mode` is kept to harvester. The only functionality attached to `buffer_handling_mode` is the `worker_image_aquisition` function which does nothing special for the string `NewestOnly`.

**Comment by blaine141** [comment]
Oh, sorry. Didn't realize you fixed this on your branch. Let me try it out

**Comment by blaine141** [comment]
My camera (FLIR Blackfly) does not support `NewestOnly`. The only option listed was `OldestFirst`. Once I commented that part of your code out, it worked well with a smaller delay. Do you know of any other ways to decrease delay?

**Comment by kazunarikudo** [comment]
Hi, if your GenTL Producer does not support `NewestOnly` then reducing the number of buffers is the only way you can minimize the delay. While a Harvester is running an image acquisition task as a thread, it uses a single buffer on the Harvester side; it overwrites the content if the GenTL Producer offers a new image. However, in general, a GenTL Producer needs two or more buffers so it eventually makes some delay. If you need to have the exact latest data, you will need to find a GenTL Producer that supports `NewestOnly` mode. Perhaps FLIR guys could be happy to help you by implementing that mode. Good luck!
