### ISSUE TITLE
Can we use harvester package for Roboception

### ISSUE THREAD

**Issue by itsmedralpha** [genicam/harvesters#340]
**What is the goal that you want to achieve by the request?**
Please describe a clear and concise description of what the motivation is. For example:

As a user, I expect Harvester does not to block other threads while it is executing the `fetch` method call because my application needs to keep being reactive.

**Additional context**
I would guess a situation where the `fetch` method call can't achieve the expected outcome, for example, no buffer was delivered, etc. In such a case, it would be great if we could have a way to understand that the `fetch` call did not deliver anything to us.

will this harvester package support Roboception cameras because roboception have Gigevision/Genicam, so if this support then how can we use it is there any tutorial available to connect with harvester please reply

**Comment by kazunarikudo** [comment]
@itsmedralpha Hi, thank you for the message. To not block your application, you need to start image acquisition by calling `ImageAcquirer.start(run_as_thread=True)`; and then you will have the following options to fetch a buffer:

1. Fetch a buffer by calling `ImageAcquirer.try_fetch(timeout=a_float)`, or
2. Fetch a buffer when the `ImageAcquirer.Events.NEW_BUFFER_AVAILABLE` event is emitted.

On the former option, you will get `None` if no data turned available during the specified period; you will periodically call the method when you are available.  On the latter option, you will be notified by the `ImageAcquirer` object when a buffer turned available to be fetched; it may not be straightforward but [this piece](https://github.com/genicam/harvesters/blob/b1e09bc68303ba86c023501ebf1566b8974ca685/src/harvesters/test/test_harvester_core.py#L615) may help you to understand how you can achieve that; I need to excuse myself because I know I need to prepare dedicated pieces of code samples for users but not for my testing purpose.

Anyway, please feel free to tell me if you should have any questions. Regards, Kazunari.

**Comment by kazunarikudo** [comment]
Closing. Please feel free to reopen if needed.
