### ISSUE TITLE
Crash when immediately stopping the image acquirer

### ISSUE THREAD

**Issue by creiter64** [genicam/harvesters#390]
**Describe the Issue**
I'm trying to run harvesters with with a GigE Vision camera, but if I start an image acquisition and immediately stop it, python crashes with the attached traceback.

**To Reproduce**

Execute the following sample code with `python.exe .\test.py`
**Sample Code**

```
from harvesters.core import Harvester as HarvesterCore
import time

hc = HarvesterCore()
hc.add_file("C:/Program Files/MATRIX VISION/mvIMPACT Acquire/bin/x64/mvGenTLProducer.cti")
print(hc.files)
hc.update()
image_src = hc.create(0)
image_src.start()
image_src.stop()  # dead

print ("pause")
```

The following traceback happens:
[traceback.txt](https://github.com/genicam/harvesters/files/10661780/traceback.txt)
 
**Expected Behavior**
This sequence of calls should not crash.

**Screenshots**
If applicable, add screenshots to help explain your problem; Note that it is not necessary to put everything as a screenshot! If the source is a text just paste the text because that is much helpful for us.

**Configuration**

 - OS: Windows 11
 - Python: Python 3.10.4
 - Harvester: https://github.com/genicam/harvesters/commit/3b2333c250e2e54725721d4affb71619244dba79
 - GenTL Producer: MATRIX-VISION mvIMPACT Acquire 2.48.0
 - Camera doesn't seem to matter

**Reproducibility**

This phenomenon can be stably reproduced:

- [x] Yes
- [ ] No.

**Actions You Have Taken**

I have tried with harvesters 1.4.0, same result.
 
- [x] I've read the [Harvester FAQ page](https://github.com/genicam/harvesters/wiki/FAQ).

**Comment by psoftware** [comment]
@kazunarikudo I've checked the GenTL spec and found that my pull request #382 is not correct and it is probably the cause of this issue.

`_flush_buffers` method is implemented using `DSFlushQueue` with the `ACQ_QUEUE_ALL_DISCARD` command, which flushes all buffers from all queues and additionally it _revokes_ all of them, which is the thing I missed.
Because I wrongly implemented the `ACQ_QUEUE_ALL_DISCARD` in my producer by not revoking the buffers, I was not seeing the issue in my tests.

Subsequent calls to revoke_buffer fail due to this.

The best solution would be to remove the for loop which revokes all the buffers because _flush_buffers already takes care of that. (but the revoke debug message would disappear too)

My sincere apologies
