### ISSUE TITLE
The create_image_acquirer raises ValueError if it's called from the outside of the main thread.

### ISSUE THREAD

**Issue by kazunarikudo** [genicam/harvesters#81]
**Describe the bug**
The `create_image_acquirer` raises `ValueError` with the message which says `signal only works in main thread` if it's called from the outside of the main thread.

**To Reproduce**
1. Define a `threading.Thread` object that tries to create an `ImageAcquirer` object calling the `create_image_acquirer` method.
2. Instantiate the thread object.
3. You'll see it raises the `ValueError` exception.

**Expected behavior**
The `create_image_acquirer` must allow clients to create an `ImageAcquirer` object no matter where it's called.

**Additional context**
None.

**Comment by lmarga** [comment]
Hi, not sure if it is the same issue but I am getting the same exception message "signal only works in main thread". If I run my code on python console it run smoothly, but I am implementing and APIREST interface with falcon+waitress and when calling `create_image_acquirer` from an on_post method I get that exception.
Python 3.6.8, harvester 0.2.8 (originaly), then I updated to 1.2.0 because of the milestone of version 0.2.10. Same results on both versions.

**Comment by lmarga** [comment]
Let me check again, harvester was not updates to 1.2.0 but I believed that it was. Still checking... Sorry!

**Comment by lmarga** [comment]
I am very sorry! Just updated to 0.2.10 and it worked! I need more work to update to 1.2.0, but I will do in the near future. Thank you very much!
